Apriori

Apriori finds frequent item sets and association rules like:
“People who buy bread also buy milk.”
This is called Market Basket Analysis.



Install Apriori library

In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (2.4.1)
Requirement already satisfied: pandas>=2.3.3 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\digi\documents\ml_practice\jupyter_env\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)


Load the dataset

In [6]:
transactions = []

with open("groceries.csv", "r") as file:
    for line in file:
        items = line.strip().split(",")
        transactions.append(items)

transactions[:5]

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product']]


Convert to Apriori format

In [7]:
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_ary, columns=te.columns_)
df_encoded.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False


Run Apriori

In [8]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(
    df_encoded,
    min_support=0.01,
    use_colnames=True
)

frequent_itemsets.sort_values(by="support", ascending=False).head(10)

     support            itemsets
85  0.255516        (whole milk)
55  0.193493  (other vegetables)
65  0.183935        (rolls/buns)
74  0.174377              (soda)
86  0.139502            (yogurt)
6   0.110524     (bottled water)
66  0.108998   (root vegetables)
80  0.104931    (tropical fruit)
72  0.098526     (shopping bags)
69  0.093950           (sausage)


Generate association rules

In [9]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.5
)

rules[["antecedents", "consequents", "support", "confidence", "lift"]].head(10)

,antecedents,consequents,support,confidence,lift
0,"(other vegetables, butter)",(whole milk),0.011490,0.573604,2.244885
1,"(root vegetables, citrus fruit)",(other vegetables),0.010371,0.586207,3.029608
2,"(curd, yogurt)",(whole milk),0.010066,0.582353,2.279125
3,"(other vegetables, domestic eggs)",(whole milk),0.012303,0.552511,2.162336
4,"(other vegetables, pip fruit)",(whole milk),0.013523,0.517510,2.025351
5,"(root vegetables, rolls/buns)",(other vegetables),0.012201,0.502092,2.594890
6,"(root vegetables, tropical fruit)",(other vegetables),0.012303,0.584541,3.020999
7,"(root vegetables, yogurt)",(other vegetables),0.012913,0.500000,2.584078
8,"(other vegetables, whipped/sour cream)",(whole milk),0.014642,0.507042,1.984385
9,"(other vegetables, yogurt)",(whole milk),0.022267,0.512881,2.007235